server:
  port: 8083
  forward-headers-strategy: native
spring:
  application:
    name: selmag-customer-app
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@localhost:8888